### PR TITLE
Work around weird Boolean behavior (in Rails?)

### PR DESCRIPTION
**Pull request by mltsy**
There's a documented weird behavior with Virtus Boolean attributes in some contexts (see Virtus readme) - this fixes it for this class.

### CODE REVIEW

**Comment by pcreux** [comment]
Oh, could you elaborate a bit? 🙂

**Comment by mltsy** [comment]
Oh hey, sure! :)  I'm not 100% sure what gem is creating it, but in my app there's a global `Boolean` constant defined, so when you say `attribute :required, Boolean` it's trying to use that class instead of the Virtus-based Boolean that you're going for.

For me the result of this was that I got an error about `required?` not being a method on ColumnDefinition (raised from somewhere in the CSVImporter code)

The Virtus gem has [a comment about this in the Readme](https://github.com/solnic/virtus#important-note-about-boolean-type), although it says to use `Axiom::Types::Boolean` as a workaround - which I believe might be a mistake, because I tried that and it still didn't work.  I feel like it's supposed to be `Virtus::Attribute::Boolean` (mainly because that's defined by Virtus, and also... it works) 😉

**Comment by pcreux** [comment]
Interesting. Can you double check that `Virtus::Attributes::Boolean` is defined in Virtus 1 and Virtus 2? I just want to make sure that we don't introduce a regression for some versions of Virtus.

**Comment by mltsy** [comment]
Ah, good idea - except... I don't think there actually is a Virtus 2 (unless I'm mistaken?)! I saw there was a mention of it in the README, but from what I can tell (also from the README), @solnic abandoned the idea of Virtus 2 in favor of 3 new gems that separate and encompass most of the responsibilities of virtus: dry-types, dry-struct and dry-validation.

So... while that doesn't bode well for the future support of Virtus (looks like it's been abandoned for over a year now), at least that should preclude the issue of having future compatibility issues 😄

**Pull request merged**
